[tool.poetry]
name = "code-rabbit-test"
version = "0.1.0"
description = ""
authors = ["naoyamada"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
